pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
               sh 'cd coit-backend1 && mvn install'
            }
        }
        stage('docker-build') {
            steps {
               sh 'echo "Docker Build"'
               sh 'cd coit-backend1 && docker build -t karthick0202/vignesh:v2 .'
               sh 'docker images' 
            }
        }
        stage('docker-push') {
            steps {
                sh 'echo "Docker Push"'
                sh 'echo "pushing docker image"'
                sh 'docker push karthick0202/vignesh'
            }
    }
}
}
