@Library("my-shared-lib@main") _
pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                 demoShared()
                //sh 'echo "mvn install"'
                //sh 'cd coit-backend1 && mvn install'
            }
        }
        stage('docker-build') {
            steps {
               sh 'echo "Docker Build"' 
            }
        }
        stage('docker-push') {
            steps {
                sh 'echo "Docker Push"'
                //sh 'echo "pushing docker image"'
                //sh 'docker push karthick0202/vignesh:v2'
            }
    }
}
}
